### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by saurav529** [manjillama/user-login-php#1]
Not working properly!! The CSS and the js scripts are not linked properly.

**Comment by manjillama** [comment]
Hi Saurav, this application is about 4+ years old now and is using outdated version of Php. You can still get the gist of it by going through codes. But I'm afraid that's all you can get the most out of it. Happy coding.

**Comment by saurav529** [comment]
Thanks brother!!!

**Comment by saurav529** [comment]
Thanks, brother!!!
